<?php

namespace Tests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Redis;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication,RefreshDatabase,WithFaker;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Redis::del(['trending_threads']);
    }
}
